# Generated by Django 4.2.15 on 2025-02-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_ticketorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='train_ticket',
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='seat_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='train_cruise',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.traincruise'),
        ),
        migrations.AddField(
            model_name='traincruise',
            name='price',
            field=models.IntegerField(default=2),
        ),
    ]
