# Generated by Django 4.2.15 on 2025-02-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_ticketorder_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincruise',
            name='seat_count',
            field=models.IntegerField(default=50),
        ),
    ]
