# Generated by Django 4.2.15 on 2025-02-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_traincruise_seat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='train_cruise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.traincruise'),
        ),
    ]
