# Generated by Django 4.2.15 on 2025-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_ticketorder_train_cruise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biometricprofile',
            name='face_data',
        ),
        migrations.AddField(
            model_name='biometricprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='biometric_faces/'),
        ),
    ]
