# Generated by Django 4.2.15 on 2025-02-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0004_userorder_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='is_take_in_robot',
            field=models.BooleanField(default=False),
        ),
    ]
