# Generated by Django 4.2.15 on 2025-02-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0005_userorder_is_take_in_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='seat',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
